### ISSUE TITLE
Error on reconnect attempt

### ISSUE THREAD

**Issue by beaston02** [ZombieAlex/mfcauto.py#2]
When a connection fails, it attempts to reconnect, but throws an error:

`TypeError: coroutines cannot be used with call_at()`

changing line 195 of client.py from 
`self.loop.call_later(30, self.connect, self._logged_in)`
to
`self.loop.call_later(30, lambda: asyncio.async(self.connect(self._logged_in)))`

fixes the issue.

**Comment by ZombieAlex** [comment]
Makes sense. Thanks for the report and the fix.

This package still isn't as well tested as the NodeJS version. So please let me know if you hit any more issues. PRs are also welcome.
