### ISSUE TITLE
Tags are appended to a model each time find_models is ran in a loop

### ISSUE THREAD

**Issue by beaston02** [ZombieAlex/mfcauto.py#5]
When running the mfcauto.Model.find_models in a loop, the tags are appended to the model in each check. So if a models tags are "tag1, tag2", the next run it will be "tag1, tag2, tag1, tag2" and "tag1, tag2, tag1, tag2, tag1, tag2" on the third run, and so on. 

[Here is an example of the code Im using to build the list of models](https://gist.githubusercontent.com/beaston02/d11c5e5999a16a6839b0f6d00181fe55/raw/fda7d731927f56de0d5e04465073737986e32c00/mfc_online_models_example.py), with the addition of a while loop printing the tags for the first listed model as an example of how the list of tags continuously grow on each check

Also, some of the servers do not support websocket connections. I have not checked in some time, but as of a few months back, the following servers do not allow connections, so will fail if/when the script attempts to connect to them: ['xchat50', 'xchat51', 'xchat52', 'xchat53', 'xchat54']

**Comment by ZombieAlex** [comment]
Tags should probably be a `set` rather than a `list`.
